### ISSUE TITLE
[VideoFFMPEGPlayer] Linking error related to JavaCPP

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#107]
When using `loadVideo`

```
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Warning: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Warning: Could not load BytePointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
```

**Comment by kureta** [comment]
Hey @ricardomatias did you ever solve this problem?

**Comment by kureta** [comment]
Trying to play video from v4l2loopback device using `VideoPlayerFFMPEG.fromDevice("/dev/video4")`. I am streaming a test video from gstreamer via `gst-launch-1.0 -v videotestsrc ! v4l2sink device=/dev/video4`. It shows a single frame, gives the following warning, and then frame freezes.
```
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Warning: Could not load Pointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Warning: Could not load BytePointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Warning: Could not load PointerPointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
Warning: Could not load IntPointer: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
```
I have no problem playing it via `gst-launch-1.0 v4l2src device=/dev/video4 ! videoconvert ! autovideosink` or from Praxis LIVE v5.

**Comment by ricardomatias** [comment]
@kureta not sure if anything changed, my lack of details on the issue doesn't help figuring that out.

**Comment by edwinRNDR** [comment]
@kureta I don't think the warning is a cause to your problem. I am also still not sure what causes these errors.

Can you try to play that `/dev/video4/` source through ffplay? Since that is a lot closer to the video infrastructure OPENRNDR is using.

**Comment by edwinRNDR** [comment]
It looks like those warnings can be safely ignored (I'd rather see them disappear but I am sure we will see that in some future version of javacpp): https://github.com/bytedeco/javacpp/issues/418#issuecomment-666310041

**Comment by kureta** [comment]
@edwinRNDR Turns out it was a problem with the video format. I added a `videoconvert` to my gstreamer pipeline and everything works now. Thanks for pointing out that the warnings were unrelated to my problem.

**Comment by hamoid** [comment]
Can this be closed or is it still an issue?

**Comment by edwinRNDR** [comment]
Closing the issue because it is old and not enough context is provided to determine if it is still relevant.
