### ISSUE TITLE
Windows ffmpeg defaultDevice

### ISSUE THREAD

**Issue by micuat** [openrndr/openrndr#111]
**Describe the bug**
ffmpeg `defaultDevice` is hardcoded as  `"Integrated Webcam"` which is unlikely to work :( I had to set device name manually (e.g. `"Microsoft Camera Front"` for MS Surface)

https://github.com/openrndr/openrndr/blob/c682be46e2cab23954a8f27f471c84170fb69688/openrndr-ffmpeg/src/main/kotlin/org/openrndr/ffmpeg/VideoPlayerFFMPEG.kt#L368

**To Reproduce**
https://guide.openrndr.org/#/09_Videos/C00_Playing_Videos?id=video-from-camera-devices

**Expected behavior**
read the list of devices and pick the first device name?

**Context:**
 - Windows 10

**Comment by hamoid** [comment]
Hi! You can set the device name in `.fromDevice()`, right? 

https://github.com/openrndr/openrndr/blob/master/openrndr-ffmpeg/src/main/kotlin/org/openrndr/ffmpeg/VideoPlayerFFMPEG.kt#L345

But maybe some examples should be shown in the guide. 
Printing a list (if possible) would be cool too.

**Comment by edwinRNDR** [comment]
Good point! One can get the list of devices using `VideoPlayerFFMPEG.listDeviceNames()`. Using the first entry from this list instead of the current hardcoded one should improve things a bit.
