### ISSUE TITLE
Allow specifying monitor for full screen window

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#113]
**Is your feature request related to a problem?**
Users with two monitors can't specify in which one to show the full screen window

**Describe the solution you'd like**
An integer in `configuration` to specify the number of the monitor to use.

**Comment by capital-G** [comment]
Is there an easy workaround on macOS available? I am using openrndr for a perfomance tomorrow and still using it in window mode because of this issue because it spawns on the wrong monitor :/

It is not possible to use mission control like how this would be normally done for some reason

**Comment by hamoid** [comment]
Hi! Too late for your performance... How did it go?

OPENRNDR uses GLFW. By looking at their documentation I find this: https://www.glfw.org/docs/3.0/monitor.html

Which led me to this file in OPENRNDR: ApplicationGLFWGL3.kt which contains a few calls to `glfwGetPrimaryMonitor()`. Maybe those need to be changed?
