### ISSUE TITLE
Poor drawing performance compared to Processing

### ISSUE THREAD

**Issue by alexdmiller** [openrndr/openrndr#12]
**Describe the bug**

[Processing](http://processing.org) significantly outperforms OPENRNDR at drawing rectangles to the screen. On my machine, Processing can draw 1000 rectangles to the screen at around 58 FPS, whereas a similar program using OPENRNDR runs at about 22 FPS.

**To Reproduce**

Run the following code in Processing:

```java
void setup() {
  size(1000, 1000);
}

void draw() {
  background(0);
  fill(255);
  noStroke();
  
  for (int i = 0; i < 1000; i++) {
    rect(random(width), random(height), 10, 10);  
  }
  
  println(frameCount / (millis() / 1000.0));
}
```

Then run the following code in an OPENRNDR project:

```kotlin
import org.openrndr.*
import org.openrndr.color.ColorRGBa

class TemplateProgram: Program() {
    var numFrames = 0

    override fun draw() {
        drawer.background(ColorRGBa.BLACK)
        drawer.fill = ColorRGBa.WHITE
        drawer.stroke = null
        for (i in 0 until 1000) {
            drawer.rectangle(Math.random() * width, Math.random() * height, 10.0, 10.0)
        }

        println(numFrames / seconds)

        numFrames++
    }
}

fun main(args: Array<String>) {
    application(TemplateProgram(),
            configuration {
                width = 1000
                height = 1000
            })
}
```

These two programs both print out the average FPS of the program as it is running.

**Expected behavior**

I would expect the drawing performance of the two frameworks to be comparable.

**Context:**
 - OS and version: 10.11.6
 - OpenRNDR version: 0.3.19
 - Java Version: 10.0.1

**Comment by hamoid** [comment]
Hi! Did you see the example at http://guide.openrndr.org/#/Tutorial_DrawingPrimitives ? There's one titled "Drawing many primitives at once". 

Things to consider: printing may be slow. I would print once per second only:

    if (frameCount % 60 == 0) {
      println(frameRate);
    }

In Processing in P2D mode I can draw 15000 shapes at 60 fps on my 4 year old laptop with integrated graphics.

With OPENRNDR I get 60 fps drawing 10000 shapes

```
class TemplateProgram: Program() {
    private val rectangles = mutableListOf<Vector2>()
    private var frame = 0
    override fun setup() {
    }
    override fun draw() {
        drawer.stroke = null
        rectangles.clear()
        for (i in 0..9999) {
            rectangles.add(Vector2(
                    Math.random() * 400,
                    Math.random() * 400))
        }
        drawer.rectangles(rectangles, 10.0, 10.0)
        frame++
        if(frame % 60 == 0) {
            println(frame / seconds)
        }
    }
}
```

If I add one more shape, I get this error:
```
java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:527)
	at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:888)
	at org.openrndr.internal.gl3.BufferWriterGL3.write(BufferWriterGL3.kt:88)
	at org.openrndr.internal.RectangleDrawer.drawRectangles(RectangleDrawer.kt:78)
	at org.openrndr.draw.Drawer.rectangles(Drawer.kt:763)
	at TemplateProgram.draw(TemplateProgram.kt:60)
```

**Comment by edwinRNDR** [comment]
@alexdmiller Thanks for reporting this. The difference is in how drawing is handled in Processing versus how it is handled in OPENRNDR. In Processing shapes are collected and emitted in a batched draw, OPENRNDR does not do this (yet?). However as @hamoid suggested you can use the `rectangles` functionality instead to draw batches of rectangles (which is arguably less convenient in some cases).

However in some cases I think the `rectangles` function makes sense, for example in the following one liner: 
```
drawer.rectangles((0 until 1000).map { Rectangle(Math.random() * width, Math.random() * height, 100.0, 100.0) })
```

@hamoid The `BufferOverflowException` comes from a hardcoded limitation in the internal drawing code. I will make those limits dynamic (aiming for 0.3.20 release)

**Comment by alexdmiller** [comment]
Thanks for the help! I didn't realize the batch drawing functions had performance implications.

I created a small PR to add a note to the OPENRNDR guide to hint at that: https://github.com/openrndr/openrndr-guide/pull/5
