### ISSUE TITLE
Implement `,` with List in NativeFileDialog.NFD_OpenDialog

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#120]
Currently `openFileDialog` accepts a list of string for `supportedExtensions`. The items in the list are each understood as a separate filter, and one can choose one of those filters in the dialog on a drop down.

That means that if you send `listOf("JPG", "jpg")` as argument, you can choose between the first and the second, when what you really want is to show files with any of the extensions.

The way to achieve that is by using `listOf("JPG,jpg")` instead, but that is not obvious.

We should change the method so it can accept list of list of string to define groups of extensions without using the `,` character, as in `listOf(listOf("JPG", "jpg", "png"), listOf("mp3", "wav"))` which lets the user show images or sound files.

Discussion at https://openrndr.slack.com/archives/CBJGUKVSQ/p1591719969009000

**Comment by hamoid** [comment]
I think it would be convenient to implement to signatures. If you only send a list of string, it is converted to a nested list. This simplifies the case where you only care about one set of extensions.

**Comment by hamoid** [comment]
Although Kotlin does not seem to support having two methods, one with an argument of type `List<String>` and the other with type `List<List<String>>`.

...

Solved by using `@JvmName("openFileDialogFlatExtensions")` in one of the methods.

**Comment by edwinRNDR** [comment]
`@Jvmname` is exactly the way to deal with it. The reasoning is that Kotlin's type system supports it but the JVM can not see the difference between `List<A>` and `List<B>`

**Comment by hamoid** [comment]
I have it working. Will send PR soon.
