### ISSUE TITLE
Circles are rendered slightly too small

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#122]
**Describe the bug**
Circles are rendered slightly smaller than expected

**To Reproduce**
```
    program {
        extend {
            backgroundColor = ColorRGBa.WHITE
            drawer.fill = ColorRGBa.PINK
            drawer.stroke = null
            drawer.circle(drawer.bounds.position(0.0, 0.5), width * 0.5)
            drawer.circle(drawer.bounds.position(1.0, 0.5), width * 0.5)

            drawer.fill = ColorRGBa.GRAY
            drawer.rectangle(Rectangle.fromCenter(Vector2(100.0), 100.0, 100.0))
            drawer.fill = ColorRGBa.WHITE
            drawer.circle(Vector2(100.0), 50.0)
        }
    }
```

**Expected behavior**
In the image below, the large circles should touch each other, and the small circle should touch the containing rectangle.

**Screenshots**
![2020-06-26-175533_640x481_scrot](https://user-images.githubusercontent.com/108264/85876599-419e5000-b7d6-11ea-87ae-08f31863cb59.png)

**Context:**
 - OS and version: ArchLinux
 - OpenRNDR version 55b8171ed9ae93ed9db190cb697a334716e0bf63
 - Java Version 11

**Additional context**
Sometimes size doesn't matter, for example when creating isolated circles one can just add 1 or 2 pixels to the size. But I'm currently experimenting with intersections and tangents and the results are somewhat off. For example the gray circles in the next image should be tangent:
![2020-06-26-174302_640x481_scrot](https://user-images.githubusercontent.com/108264/85876925-b4a7c680-b7d6-11ea-9abd-78616932d0f9.png)

**Comment by hamoid** [comment]
As a workaround I replaced calls to `drawer.circle` with `drawer.circler` and I think it looks good then.
```
private fun Drawer.circler(c: Circle) {
    circle(c.scaledTo(c.radius + 1.5))
}
```
![2020-06-26-180404_640x481_scrot](https://user-images.githubusercontent.com/108264/85877491-8676b680-b7d7-11ea-8649-1147715bbdff.png)

The real solution is most likely not as simple as just adding a value, as it should consider stroke, shapes and maybe other aspects I'm not aware of.

**Comment by hamoid** [comment]
Another example showing that the circles are a bit smaller than their radii.
![2020-07-07-110006_677x507_scrot](https://user-images.githubusercontent.com/108264/86754437-2dade600-c041-11ea-8e70-b38666a2f0a5.png)

**Comment by hamoid** [comment]
To clean up things, I'm moving here one more comment that was inside #115 

![image](https://user-images.githubusercontent.com/108264/106380139-992a1d00-63b0-11eb-8eaf-efcf1b7c7e5a.png)

```kotlin
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.draw.*
import org.openrndr.extensions.Screenshots
import org.openrndr.shape.Circle
import org.openrndr.shape.Rectangle
import kotlin.math.sin

fun main() {
    application {
        program {
            val circle = Circle(0.0, 0.0, 10.0)

            extend(Screenshots())
            extend {
                drawer.stroke = null
                val k = 11.0 + 10 * sin(seconds)

                drawer.isolated {
                    translate(bounds.position(0.2, 0.5))
                    scale(k)
                    shape(circle.shape)
                }

                drawer.isolated {
                    translate(bounds.position(0.8, 0.5))
                    scale(k)
                    circle(circle)
                }

                drawer.isolated {
                    stroke = ColorRGBa.WHITE
                    fill = null
                    rectangle(Rectangle.fromCenter(bounds.center, 2000.0, 2 * 10.0 * k))
                }
            }
        }
    }
}
```
It seems to show that the tiny size discrepancy gets amplified by `scale()`.

**Comment by edwinRNDR** [comment]
Addressed this in https://github.com/openrndr/openrndr/commit/7d540f30f163e0e1b4c7d18a9790a2846a92b08a

**Comment by hamoid** [comment]
Much improved, specially if using scaling :+1: 
![2021-02-07-101655_640x480_scrot](https://user-images.githubusercontent.com/108264/107142240-b79e9400-692d-11eb-8680-6fa085984ce8.png)
![2021-02-07-101544_768x576_scrot](https://user-images.githubusercontent.com/108264/107142241-b8372a80-692d-11eb-821b-00c609452187.png)
