### ISSUE TITLE
Proper equals() for all classes

### ISSUE THREAD

**Issue by amollberg** [openrndr/openrndr#124]
**Is your feature request related to a problem?**
Lots of code, especially unit tests, depends on checking for equality between an expected and actual object. 
If I want to write a test that checks that some algorithm I wrote returns the correct Vector2, for example, I cannot use JUnit built-in `assertEquals()` on the Vector2 directly, but have to write a helper function e.g.
```
        fun assertEquals(a: Vector2, b: Vector2) {
            assertEquals(a.x, b.x, "$a != $b (x-coord)\n")
            assertEquals(a.y, b.y, "$a != $b (y-coord)\n")
        }
```
Things get much more complicated if other objects contain Vector2 (extremely common)...
To me it is worth implementing even considering floating-point precision concerns. 

**Describe the solution you'd like**
Override `equals()` for all classes where it makes sense. `ShapeContour` may need to be supplemented with `.coversEqualArea()` or something, if it is desired to ignore winding.

**Additional context**
Nothing specifically.
I am working on https://github.com/amollberg/ArtisanTrace but this request does not relate specifically to it; it has much broader applications.

**Comment by edwinRNDR** [comment]
Hi @amollberg, this is definitely something that needs to be looked into. However the case of classes like `Vector2` confuses me a bit, since those are data classes, and my understanding of those is that a property based `equals()` generated by the Kotlin compiler. Please correct me if I am wrong.

off-topic: nice to see sizable OPENRNDR based projects in the wild!

**Comment by edwinRNDR** [comment]
Made some steps here https://github.com/openrndr/openrndr/commit/faa5467a601b125092461af9bd472209645f3e74

**Comment by amollberg** [comment]
> However the case of classes like Vector2 confuses me a bit, since those are data classes, and my understanding of those is that a property based equals() generated by the Kotlin compiler. Please correct me if I am wrong.

I am sorry, you are correct. I must have misinterpreted the build problems when I decided to create the `fun assertEquals(a: Vector2, b: Vector2)`; I cannot produce any unexpected results now that I experiment with it. Let me know if you want me to update the original post.

**Comment by edwinRNDR** [comment]
Bit late, but I think this can be closed. Don't hesitate to reopen in case you find equals/hash implementations missing!
