### ISSUE TITLE
Add Window Closed / Application Shutdown life-cycle event

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#126]
**Is your feature request related to a problem?**
Currently, there isn't an event for cleaning up when the window is closed / application is shutting down.

**Describe the solution you'd like**
An event/hook which allows cleaning up before exiting.

**Additional context**
[Discourse Thread](https://openrndr.discourse.group/t/callback-when-window-has-been-closed-by-user/125/9)

**Comment by driceduconge** [comment]
hello, this doesn't seem to work, even in a black openrndr-template whenever I call window.closed.listen it doesn't seem to work ? there isn't any way for it to print anything either ? I tried looking it up but nothing shows up on that matter

**Comment by edwinRNDR** [comment]
hi @driceduconge, I will look into what is up with the window.closed event. You can try the following:

```
program.ended.listen {
    println("program ended")
}
```

**Comment by driceduconge** [comment]
Thanks! It works perfectly this way !
