### ISSUE TITLE
[CatmullRomChain2] Doesn't include the start/end points

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#128]
**Describe the bug**
The first and last points provided aren't included in the resulting catmull-rom interpolation.

<img width="466" alt="Screenshot 2020-07-02 at 16 32 46" src="https://user-images.githubusercontent.com/8850708/86373305-91bc5d00-bc83-11ea-8266-8f11ec55dbac.png">

**Comment by edwinRNDR** [comment]
https://github.com/openrndr/openrndr/pull/130 settles it, right?

**Comment by ricardomatias** [comment]
Yes
