### ISSUE TITLE
[Mouse] Dragged event doesn't include keyboard modifiers

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#133]
**Describe the bug**
The `mouse.dragged` listener doesn't include `Shift, Control, Alt` keyboard modifiers.

**Context:**
 - OS and version: [e.g. macOS 10.13.3]: Linux Pop_OS 20.04
 - OpenRNDR version : 0.3.43
 - Java Version: 14

**Comment by hamoid** [comment]
Somewhat related:
https://github.com/openrndr/openrndr/pull/117
https://github.com/openrndr/openrndr/commit/e08ef84cc6a8672cd0e4f17e5f4e474787cd8e93

**Comment by hamoid** [comment]
Related to #127 

A test program:

```
fun main() = application {
    program {
        extend { }
        mouse.dragged.listen {
            print("dragged: ")
            println(it.modifiers)
        }
        mouse.buttonDown.listen {
            print("button down: ")
            println(it.modifiers)
        }
        keyboard.keyDown.listen {
            print("key down: ")
            println(it.modifiers)
        }
    }
}
```

One interesting fact is that at least in Linux, the modifiers for button down are not the same as for dragged. 
So if I hold down CTRL+SHIFT, click and drag, it shows CTRL+SHIFT for click but only the first one of the two for drag.
