### ISSUE TITLE
[ShapeContour] Using equidistantPositions on a contour derived from a Rectangle leads to points outside of it

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#135]
**Describe the bug**
When doing `Rectangle(100.0, 100.0, 300.0, 300.0).contour.equidistantPositions(10)`, the result is:

![Screenshot from 2020-07-11 15-35-16](https://user-images.githubusercontent.com/8850708/87225490-b3a59600-c38d-11ea-8e4f-335374376294.png)

All the points should be on the contour.

**Comment by hamoid** [comment]
I like the images as an art piece :)
