### ISSUE TITLE
Drawer.lineSegments() rendering issue

### ISSUE THREAD

**Issue by kles4enko** [openrndr/openrndr#155]
**Describe the bug**
Lines color looks wrong when using `Drawer.lineSegments()`

**To Reproduce**
```kotlin
fun main() = application {
    configure {
        width = 1000
        height = 1000
    }

    program {
        val points = mutableListOf<Vector2>()
        val pointsCount = 400
        val linesColor: ColorRGBa = ColorRGBa.WHITE.copy(a = 0.35)

        for (i in 0 until pointsCount) {
            points.add(
                Vector2(
                    x = random(max = width.toDouble()),
                    y = random(max = width.toDouble())
                )
            )
        }

        extend(Screenshots()) {
            scale = 2.0
        }

        extend {
            drawer.fill = null
            drawer.stroke = linesColor
            drawer.strokeWeight = 2.0

            drawer.lineSegments(points)
        }
    }
}
```

**Expected behavior**
Expected that it will rendering correct, like `Drawer.lineSegment()` does it.
```kotlin
fun main() = application {
    configure {
        width = 1000
        height = 1000
    }

    program {
        val points = mutableListOf<Vector2>()
        val pointsCount = 400
        val linesColor: ColorRGBa = ColorRGBa.WHITE.copy(a = 0.35)

        for (i in 0 until pointsCount) {
            points.add(
                Vector2(
                    x = random(max = width.toDouble()),
                    y = random(max = width.toDouble())
                )
            )
        }

        extend(Screenshots()) {
            scale = 2.0
        }

        extend {
            drawer.fill = null
            drawer.stroke = linesColor
            drawer.strokeWeight = 2.0

            for (i in 0 until pointsCount step 2) {
                val point1 = points[i]
                val point2 = points[i+1]
                drawer.lineSegment(point1, point2)
            }
        }
    }
}
```

**Screenshots**
`Drawer.lineSegments()`
![galines LinesBug-2020-08-27-23 13 07](https://user-images.githubusercontent.com/1761252/91492185-e49a4580-e8bd-11ea-995b-4558dfa0a632.png)

`Drawer.lineSegment()`
![galines LinesBug-2020-08-27-23 22 47](https://user-images.githubusercontent.com/1761252/91492223-f7147f00-e8bd-11ea-9b24-c8760ecccbe0.png)

**Context:**
 - MacOS 10.15.6 (Macbook pro 2019 with Radeon card)
 - OpenRNDR 0.3.43
 - Java 8,11,14.. doesn't matter.
 - Driver:
```
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ 3.4.0 Cocoa NSGL EGL OSMesa dynamic
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL vendor: ATI Technologies Inc.
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL renderer: AMD Radeon Pro 560X OpenGL Engine
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL version: 4.1 ATI-3.10.16
```

**Comment by hamoid** [comment]
Hi! I see two issues, one I think is expected and the other not.

When drawing using `lineSegments` I would say it is expected that the intersections are not brighter. That is because all the lines are drawn in one pass to make it faster. If one needs lines to interact with previously drawn lines using `lineSegment` multiple times is probably a better approach.

But another issue is that there is some kind of tiny noise in the intersections, like single bright pixels. Ideally that would not happen. Maybe it comes from how antialiasing / smoothing is done?

I'm sure @edwinRNDR can say more about these.

**Comment by kles4enko** [comment]
@hamoid Thanks for the tips!
Originally I had more complex sketch. I just simplified code to show the issue.

**Comment by hamoid** [comment]
Update: the noise issue is greatly improved by switching from

        val linesColor = ColorRGBa.WHITE.opacify(0.35)

to

        val linesColor = ColorRGBa.WHITE.opacify(0.59).alphaMultiplied

**Comment by edwinRNDR** [comment]
It is the result of an optimization (single stencil pass). You could abuse the 3d line drawing, which does not use stenciling to get the desired blending.

**Comment by hamoid** [comment]
Ah simple. Just change `Vector2` for `Vector3`. And probably add `multisample` to make the lines look good.

```
import org.openrndr.WindowMultisample
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.extensions.Screenshots
import org.openrndr.extra.noise.Random
import org.openrndr.math.Vector3

fun main() = application {
    configure {
        width = 1000
        height = 1000
        multisample = WindowMultisample.SampleCount(8)
    }

    program {
        val points = List(400) {
            Vector3(
                Random.double0(width.toDouble()),
                Random.double0(width.toDouble()),
                0.0
            )
        }

        extend(Screenshots()) {
            contentScale = 2.0
        }

        extend {
            drawer.stroke = ColorRGBa.WHITE.opacify(0.35)
            drawer.strokeWeight = 2.0
            drawer.lineSegments(points)
        }
    }
}
```

![sketches Paths3D-2024-02-12-12 03 05](https://github.com/openrndr/openrndr/assets/108264/69fc4530-ef28-40c5-82f1-bad01fb8df81)
