### ISSUE TITLE
[ShapeContour] Using drawer.contours fills the shapes incorrectly

### ISSUE THREAD

**Issue by Jorkoh** [openrndr/openrndr#157]
**Describe the bug**
Shapes are not filled correctly when using `drawer.contours()`

**To Reproduce**
```
val shape = contour {
    moveTo(Vector2(width / 2.0 - 150.0, height / 2.0 - 150.00))
    lineTo(cursor + Vector2(300.0, 0.0))
    lineTo(cursor + Vector2(0.0, 300.0))
    lineTo(cursor + Vector2(-300.0, 0.0))
    lineTo(anchor)
    close()
}
drawer.clear(ColorRGBa.PINK)
drawer.fill = ColorRGBa.WHITE
drawer.stroke = ColorRGBa.BLACK
drawer.contours(listOf(shape))
```

**Screenshots**
Using `drawer.contour(shape)`
![java_2020-08-29_19-36-50](https://user-images.githubusercontent.com/27740534/91642879-31e9f480-ea2f-11ea-817f-7670f93f9299.png)

Using `drawer.contours(listOf(shape))`
![java_2020-08-29_19-37-14](https://user-images.githubusercontent.com/27740534/91642887-40381080-ea2f-11ea-9b43-6ec48df2c976.png)

**Context:**
 - Windows 10
 - OpenRNDR 0.3.43
 - Java 11
```
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ 3.4.0 Win32 WGL EGL OSMesa VisualC DLL
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL vendor: ATI Technologies Inc.
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL renderer: Radeon (TM) RX 480 Graphics
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL version: 4.3.13586 Core Profile Forward-Compatible Context 19.12.3 26.20.15003.5016
 WARN [main] o.o.i.g.ShaderGL3               ↘ Shader 'shade-style-default:expansion' does not have a uniform called 'bounds'
 WARN [main] o.o.i.g.ShaderGL3               ↘ Shader 'shade-style-default:expansion' does not have a uniform called 'bounds'
```

**Comment by Jorkoh** [comment]
Adding an extra segment at the end of the shape is one way to get around the issue

```
val shape = contour {
    moveTo(Vector2(width / 2.0 - 150.0, height / 2.0 - 150.00))
    lineTo(cursor + Vector2(300.0, 0.0))
    lineTo(cursor + Vector2(0.0, 300.0))
    lineTo(cursor + Vector2(-300.0, 0.0))
    lineTo(cursor + Vector2(Double.MIN_VALUE, 0.0))
    lineTo(anchor)
    close()
}
```

**Comment by hamoid** [comment]
Hi! I can't reproduce that in my Linux with integrated graphics. Is your program inside an `extend { ... }` block?

**Comment by Jorkoh** [comment]
Yes, I tested it with the project template like this:
```
fun main() = application {
    program {
        extend {
            // here
        }
    }
}
```
Anyway I uninstalled IntelliJ 2019.3 and installed IntelliJ 2020.2.1 (without importing previous settings) and **it works fine** on both `0.3.43` and `0.3.44-rc.11`. I guess there was something weird with my project SDK or Kotlin plugin.

Thanks for the help!
