### ISSUE TITLE
LineJoin.ROUND affects arcTo caps

### ISSUE THREAD

**Issue by Vechro** [openrndr/openrndr#162]
**Describe the bug**
LineJoin.ROUND creates odd artifacts at the ends of arcs.

**To Reproduce**
Run the script, feel free to comment out the lineJoin part to see the difference:
```kt
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.draw.LineJoin
import org.openrndr.extra.olive.oliveProgram
import org.openrndr.math.Vector2
import org.openrndr.shape.ShapeContour
import org.openrndr.shape.contour

fun arc(start: Vector2, end: Vector2, radius: Double): ShapeContour {
    return contour {
        moveTo(start)
        arcTo(radius, radius, 0.0, false, false, end)
    }
}

fun main() = application {
    configure {
        width = 800
        height = 800
    }
    oliveProgram {
        val center = Vector2(width / 2.0, height / 2.0)
        val extra = Vector2(75.0, 75.0)

        extend {
            drawer.clear(ColorRGBa.PINK)

            drawer.lineJoin = LineJoin.ROUND

            drawer.strokeWeight = 40.0
            drawer.contour(arc(center - extra, center - extra - extra, 75.0))
            drawer.contour(arc(center, center + extra, 75.0 / 2.0))
            drawer.contour(arc(center + extra + extra, center + extra, 75.0 / 2.0))
        }
    }
}
```

**Expected behavior**
LineJoin shouldn't affect arc line caps at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/6316604/98842197-e356ce80-2451-11eb-8051-80c914352470.png)

**Context:**
 - OS and version: Windows 10, 20H2
 - OpenRNDR version: 0.3.44
 - Java Version: adoptopenjdk-openj9 15.0.1

**Comment by edwinRNDR** [comment]
This, like issue #164, is addressed by https://github.com/openrndr/openrndr/commit/a58312c4ea13f3f4721be171e5f08a9c8e61d383

**Comment by hamoid** [comment]
With the most recent changes it looks like this:
![2021-01-31-100922_441x438_scrot](https://user-images.githubusercontent.com/108264/106379450-76960500-63ac-11eb-86c2-741b725957dd.png)

Is it solved then?

**Comment by Vechro** [comment]
Looks good to me, I should've closed this earlier, thanks.
