### ISSUE TITLE
Drawing a Circle(...).contour with a small radius creates a polygonal shape

### ISSUE THREAD

**Issue by Vechro** [openrndr/openrndr#164]
**Describe the bug**
Creating a small circle using the Circle class constructor and converting it to a contour, then drawing it with any size strokeWeight creates a slightly polygonal shape instead of the expected circle.

**To Reproduce**
```kt
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.extra.olive.oliveProgram
import org.openrndr.math.Vector2
import org.openrndr.shape.Circle

fun main() = application {
    configure {
        width = 800
        height = 800
    }
    oliveProgram {
        val center = Vector2(width / 2.0, height / 2.0)

        extend {
            drawer.clear(ColorRGBa.PINK)
            drawer.strokeWeight = 128.0 // Change this value to whatever

            drawer.contour(Circle(center, 2.0).contour)
        }
    }
}
```

**Expected behavior**
It should produce a nice and smooth circle.

**Screenshots**
Instead we get something that's *almost* a circle. 
![image](https://user-images.githubusercontent.com/6316604/99142605-3fdb0900-265f-11eb-89e1-6683e9416f0c.png)

**Context:**
 - OS and version: Windows 10, 20H2
 - OpenRNDR version: 0.3.44
 - Java Version: AdoptOpenJDK OpenJ9 15.0.1+9

**Comment by edwinRNDR** [comment]
This is addressed by https://github.com/openrndr/openrndr/commit/a58312c4ea13f3f4721be171e5f08a9c8e61d383

Will release OPENRNDR 0.3.45-rc.3 later today, which will include that fix

**Comment by Vechro** [comment]
The example code indeed now works fine, although trying to draw small circles with a `strokeWeight` of say `10.0` still produces odd behavior. Possibly due to the subdivision code. 
![image](https://user-images.githubusercontent.com/6316604/99186186-56648b80-2757-11eb-8884-f93a2f461f6a.png)

**Comment by hamoid** [comment]
Issue no longer present, closing.
