### ISSUE TITLE
How to do contour subtraction?

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#167]
I'm trying to get contours to be clipped by other contours drawn on top. In the following picture you can see 3 circles, red one is for the contour that was drawn first, the yellow one for the contour that was drawn after and in green a triangle which I'm trying to get rid of. Is there a way to get rid of it with clipping?

![Screenshot from 2020-11-26 17-38-09](https://user-images.githubusercontent.com/8850708/100753152-b6ab2c80-33e9-11eb-8ced-8b1ff7d714ff.png)

I mentioned this in slack, to which edwin replied:
`you'd need something like subtract (or difference) but with the operands inverted`

I attempted to use the intersections to figure out which segments are within the intersection range and thus removing them from the cropped shaped, but it's not feasible due to lack of context f.ex, given 2 intersections points with a `t` value of 0.4 and 0.6, is the range between 0.4 - 0.6 or 0.0 -> 0.4 and 0.6 -> 1.0?

I found the paper below on doing polygon subtraction, but before attempting to implement it is there already a way of doing it in OPENRNDR?

[Polygon subtraction in two dimensions](https://www.pnnl.gov/main/publications/external/technical_reports/PNNL-SA-97135.pdf)

**Comment by ricardomatias** [comment]
Test for the new clip mode `REVERSE_DIFFERENCE` below and SVG found [here](https://gist.github.com/ricardomatias/5abd4efa1247e13837f06bb370eed757)

```kotlin
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.shape.ClipMode
import org.openrndr.shape.drawComposition
import org.openrndr.svg.loadSVG

fun main() {
    application {
        configure {
            width = 1080
            height = 1080
        }
        program {
            val cd = loadSVG("data/output.svg") 
            val patches = cd.findShapes().reversed() 
            val newComposition = drawComposition {
                stroke = ColorRGBa.BLACK
                strokeWeight = 2.0
                clipMode = ClipMode.REVERSE_DIFFERENCE
                for (patch in patches) {
                    shape(patch.shape)
                }
            }
            extend {
                drawer.clear(ColorRGBa.PINK)
                drawer.composition(newComposition)
            }
        }
    }
}
```

**Comment by rcyrus** [comment]
I am also very interested in this capability. [This post](https://openrndr.discourse.group/t/testing-compositiondrawer-clip-modes/183) in OPENRNDRs forum is relevant i think otherwise I have some ideas on how to "flatten" a composition but have yet to write them up.

**Comment by ricardomatias** [comment]
Closing this issue, it's solved by the introduction of `ClipMode.REVERSE_DIFFERENCE`
