### ISSUE TITLE
Request: implement rectMode from Processing

### ISSUE THREAD

**Issue by jmg-duarte** [openrndr/openrndr#17]
As the title states [rectMode()](https://processing.org/reference/rectMode_.html) would be very useful for the same reasons it is useful in Processing.

I don't have much Kotlin experience or with the OpenRNDR API but I could try and implement it, is there any guide or even a Javadoc style documentation for OpenRNDR?

Thank you in advance!

**Comment by edwinRNDR** [comment]
@jmg-duarte I am inclined to not have a `rectMode` as it introduces extra state to the drawer and I believe most of it can be solved at the point of supplying the rectangle to be drawn. 

for example:
```
drawer.rectangle(Rectangle.fromCenter(100.0, 100.0, 50.0, 50.0))
```

Can you point out (apart from the overhead in extra characters to type) if rectMode serves a purpose that I have now glanced over?

**Comment by jmg-duarte** [comment]
In Processing, `rectMode` influences the axis over which the rectangle rotates

**Comment by hamoid** [comment]
For what it's worth, OF also implements this:
https://openframeworks.cc/documentation/graphics/ofGraphics/#show_ofSetRectMode

**Comment by ertdfgcvb** [comment]
I second Edwin‘s thought on this. And keeping track of the extra state causes more trouble than benefits in my opinion.

**Comment by jmg-duarte** [comment]
Alright! Let's close this then
