### ISSUE TITLE
mouse.position.y contains fractional values when using i3wm

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#175]
**Describe the bug**
`mouse.position.y` contains fractional values. It seems to be calculated against an off-by-one screen height value. The `.x` value contains whole numbers as expected.

**To Reproduce**
print `mouse.position.y` while moving the mouse

**Expected behavior**
I expected the y value to also be whole numbers

**Screenshots**
See the .y value at the bottom of https://user-images.githubusercontent.com/108264/103518935-e8923180-4e74-11eb-880e-46e5df667438.png

**Context:**
 - Ubuntu 20.04, Nvidia drivers
 - OpenRNDR from git

**Comment by hamoid** [comment]
The odd vertical scaling happens when using i3wm. With the default Ubuntu display manager the vertical scale is 1.0 as expected, so I will close this issue.

The linked issue #171 is not affected by using or not using i3wm. In both cases the text is blurred.

**Comment by edwinRNDR** [comment]
I already suspected that was the issue. I thought I ignored the vertical scaling altogether (and use the horizontal one, which appears to be much better behaved), but maybe not for the mouse

**Comment by edwinRNDR** [comment]
Turns out I never ignored the vertical scaling, I pushed some code that addresses that. Curious if that makes a difference for you

**Comment by hamoid** [comment]
I don't see it pushed yet, but I will testing as soon as it's there :)

**Comment by edwinRNDR** [comment]
It is there now :)

**Comment by hamoid** [comment]
`println(window.scale)` oddly continues to output `Vector2(x=1.0, y=1.0015772581100464)`. 
But I can do `mouse.position.round(0)` and that's good enough for my current program.

**Comment by hamoid** [comment]
Related side effect: ScreenRecorder() with a screen height of 720 fails saying that you can't export video with an odd height (719). So I must set it to 721 to export at 720 ¯\_(ツ)_/¯

Yes yes, I should try https://swaywm.org/ :-)
