### ISSUE TITLE
Specifying a fixed frame rate

### ISSUE THREAD

**Issue by dnasseri** [openrndr/openrndr#187]
Hello there, is there any API or configuration exposed to fix the "framerate", ie how many times extend is executed per second?

**Comment by hamoid** [comment]
Not sure, but there's this: https://openrndr.discourse.group/t/running-a-program-at-a-specific-frame-rate/144

**Comment by dnasseri** [comment]
> Not sure, but there's this: https://openrndr.discourse.group/t/running-a-program-at-a-specific-frame-rate/144

Thanks, I will check out some of the methods in that discussion and follow up there.
