### ISSUE TITLE
Add INT32 and UINT32 image types for atomic operations

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#188]
From the spec

> Referring to the latest GLSL specification, version 4.50, revision 5 (although this language has always existed), section 8.12, bottom of page 175, it says:
> 
> Atomic memory operations are supported on only a subset of all image variable types; image must be either:
> 
> • a signed integer image variable (type starts “iimage”) and a format qualifier of r32i, used with a data argument of type int, or
> 
> • an unsigned image variable (type starts “uimage”) and a format qualifier of r32ui, used with a data argument of type uint.
> 
> Image atomics are only accepted on integer image types with a format qualifier of r32i or r32ui.

**Comment by hamoid** [comment]
Could you provide some context? What are atomic operations and when are they useful?

**Comment by ricardomatias** [comment]
This topic is very new to me, so I'll leave here a [link](https://www.khronos.org/opengl/wiki/Atomic_Counter). As far as I understood, atomic operations are used in parallel programming to enforce serial memory access. In a shader any memory can be accessed by any thread, so atomic operations are a way of making sure that the memory read/writes are done sequentially.

For future reference there are already available these types:
* `ColorType.UINT32_INT`
* `ColorType.SINT32_INT`

+ these layout qualifiers:
`size2x32 : RG32F, RG32I, RG32UI`
