### ISSUE TITLE
Should .sub() functions have consistent parameter names across classes?

### ISSUE THREAD

**Issue by Vechro** [openrndr/openrndr#192]
While working on my previous PR, I noticed there's a lack of consistency for the functions that sample a subcontour of somesort.

![image](https://user-images.githubusercontent.com/6316604/107924252-54d77900-6f7b-11eb-8b86-69f0fe6ce8d9.png)

We have the subcontour starting *t* value called either: `t0`, `u0` or `startT` depending on which class you use. Wouldn't it be clearer for the user if they were consistently named? I can understand Rectangle having `u0` and `v0` but others seemingly don't really have an excuse? 

Any opinions? What should the consistent parameter naming be?

**Comment by edwinRNDR** [comment]
I'd say `t0` and `t1` where possible. I used `u0` and `u1` on the one dimensional ones because clamping (or otherwise pre-processing) input values came as an afterthought.. those instances can be converted to `t0` and `t1` as well but require a bit more thought than just renaming.

**Comment by Vechro** [comment]
Is in-function clamping something that should be done everywhere with *t* values?

**Comment by edwinRNDR** [comment]
Clamping modes depend on the topology. For example closed shape contours have modulo 1 domains. I think the current schemes for clamping are OK but I am open for counter-examples

**Comment by Vechro** [comment]
That sounds reasonable, I'll try to make a PR soon to adjust the function parameter names to `t0` and `t1`.
