### ISSUE TITLE
Extension function for applying linear transformation to List<ShapeContour>

### ISSUE THREAD

**Issue by Vechro** [openrndr/openrndr#193]
**Is your feature request related to a problem?**

Recently I was handling a few ShapeContours yet I felt the use of Shape wasn't really warranted, but I wanted to transform a list of ShapeContours. I wrote a quick extension function and thought it'd be a nice addition to the core library for others to use.

**Describe the solution you'd like**

This is my simple, very straightforward, extension function implementation.

```kt
fun List<ShapeContour>.transform(matrix: Matrix44): List<ShapeContour> =
    this.map {
        it.transform(matrix)
    }
```

Are there any thoughts about this? Would this make a good addition to OPENRNDR? I can make the PR myself if needed.

**Comment by hamoid** [comment]
I feel like it doesn't hide much complexity.

```kotlin
    // before
    myContours.map { it.transform(myMatrix) }
    // after
    myContours.transform(myMatrix)
```

It's a few characters less but the core gains one method, so not convinced yet :-)
Maybe other's can chime in?

**Comment by edwinRNDR** [comment]
I'd argue `map` covers this nicely, is available on a wider selection of containers and supports a wider set of use cases.

**Comment by Vechro** [comment]
That's fair.
