### ISSUE TITLE
Deprecate OrientedRectangle class

### ISSUE THREAD

**Issue by Vechro** [openrndr/openrndr#194]
**Is your feature request related to a problem?**

When I was documenting OrientedRectangle class, I noticed it's a really haphazard implementation of a simple Rectangle with a linear transformation. Half of the class methods return a regular Rectangle instead of another OrientedRectangle as one would expect. It's easy enough to just create a regular Rectangle and apply a transformation yourself without any unnecessary surprises.

**Describe the solution you'd like**

So my suggestion would be to deprecate OrientedRectangle for the time being. This is to discourage any further use of the half-baked class. 

Any thoughts or opinions?

**Comment by edwinRNDR** [comment]
I believe the `openrndr-0.4` branch has this removed, so that should resolve the issue.
