### ISSUE TITLE
cursorDisabled as Application/Mouse property

### ISSUE THREAD

**Issue by Ouroboros42** [openrndr/openrndr#199]
Currently `disableCursor` is set once in `Configuration`, and then constant for the program lifetime.

I think it should be an `Application` or `Mouse` property like `cursorVisible` so that it can be changed based on user input or other triggers.

**Comment by hamoid** [comment]
Would `application.cursorVisible` help?

For example

```kotlin
extend {
    application.cursorVisible = keyboard.pressedKeys.contains("left-alt")
}
```

to make the mouse pointer visible or invisible using the left alt key?

**Comment by Ouroboros42** [comment]
The problem with this is that `cursorVisible` only sets visibility,  but does not capture mouse movement, meaning the mouse can leave the window, which in my case is not desired behavior.
`Configuration.disableCursor` does cause the desired behavior of capturing the mouse movement, and was recently added specifically for this purpose, but only to `Configuration`, not `Application`.

**Comment by edwinRNDR** [comment]
https://github.com/openrndr/openrndr/commit/4af2e2bb0a27d46f4375065d19c2f83f6aa7e7d2 and my notes https://openrndr.discourse.group/t/pass-vertexbuffer-like-data-to-shadestyle-code/201/14?u=edwin
