### ISSUE TITLE
Incorrect horizontal layout.

### ISSUE THREAD

**Issue by Josef-Vonasek** [openrndr/openrndr#209]
**Describe the bug**
I wanted to draw the same image twice vertically. But for some reason it got rescaled in Y direction, so it shows two black boxes.

**To Reproduce**
Download template and use this code:

```kotlin
val SIZE = arrayOf(500, 500)


fun main() = application {
    configure {
        width  = SIZE[0]
        height = SIZE[1]*2
    }


    program {
        val image = loadImage("data/images/cheeta.jpg")
        val original = renderTarget(SIZE[0], SIZE[1]) { colorBuffer() }
  
       // rescale it to SIZE
        drawer.isolatedWithTarget(original) {
            drawer.image(image, 0.0, 0.0, SIZE[0]+.0, SIZE[1]+.0)
        }

       // draw vertically
        extend {
            drawer.image(original.colorBuffer(0))
            drawer.image(original.colorBuffer(0), 0.0, SIZE[1]+.0)
        }
    }
}
```

**Expected behavior**
No black boxes. Two rectangular cheeta.

**Screenshots**
![image](https://user-images.githubusercontent.com/22682767/111070353-abc86380-84d1-11eb-84e5-0d97adcd7015.png)

**Context:**
 - OS and version: Windows10
 - Java Version: openjdk-15.0.2
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ 3.4.0 Win32 WGL EGL OSMesa VisualC DLL
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL vendor: ATI Technologies Inc.
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL renderer: AMD Radeon(TM) Vega 8 Graphics
 INFO [main] o.o.i.g.ApplicationGLFWGL3      ↘ OpenGL version: 4.5.13596 Core Profile Forward-Compatible Context 20.10.35.02 27.20.1034.6

**Comment by hamoid** [comment]
See https://guide.openrndr.org/#/06_Advanced_drawing/C00_Render_targets?id=render-targets-and-projection-transformations

The call to `ortho(original)` is missing. (Thanks @ricardomatias  for the reminder)

**Comment by Josef-Vonasek** [comment]
Thank you. Could also explain why does it behave like that in the first place? And how do I for example draw two cheeta at random (x,y) correctly?

**Comment by ricardomatias** [comment]
In a nutshell, the `drawer.ortho` call changes the projection matrix which in 2D it's an orthographic projection (since there is no perspective, elements aren't far or close). If you don't call `ortho` its going to use the program's dimensions and project the image based on that.

You can check [this](https://guide.openrndr.org/#/04_Drawing_basics/C01_Images) section of the guide on how to draw images. I'd recommend reading the guide from the beginning to make your experience with OPENRNDR smoother.

**Comment by hamoid** [comment]
An example so if I ever forget I can look at this again:

Typically in computer graphics there are model, view and projection matrices. The projection matrix is used to make sure vertices are inside the render volume [-1, +1] x [-1, +1] x [-1, +1]. Two typical projection matrices are `ortho` and `perspective`.

In this program
```kotlin
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.color.rgb
import org.openrndr.draw.isolatedWithTarget
import org.openrndr.draw.renderTarget

fun main() = application {
    configure {
        width = 400
        height = 200
    }
    program {
        val canvas = renderTarget(190, 190) {
            colorBuffer()
        }
        drawer.isolatedWithTarget(canvas) {
            //ortho(canvas) // changes projection matrix
            clear(ColorRGBa.PINK)
            circle(190.0, 190.0, 20.0)
        }
        extend {
            drawer.clear(rgb(0.7))
            drawer.image(canvas.colorBuffer(0), 5.0, 5.0)
        }
    }
}
```
the default projection matrix is orthographic and matches the initial window size (400, 200). This same projection matrix is active when drawing inside `canvas`. With it, the (190, 190) location is horizontally near the center and vertically near the bottom.
![image](https://user-images.githubusercontent.com/108264/111493456-dc143a00-873d-11eb-8dba-26fa1d509742.png)

But in reality I wanted to draw the circle at the bottom right of `canvas`. To make it work make sure the projection matrix matches the current render target by calling `ortho(canvas)`. In that case the (190, 190) location is at the bottom right corner of the render target and it looks like this:

![image](https://user-images.githubusercontent.com/108264/111493487-e33b4800-873d-11eb-8cb9-b0cd0215618a.png)
