### ISSUE TITLE
Test permanently switched off - openrndr-math: TestTransforms / projections / should un-project a projected point back into 3D

### ISSUE THREAD

**Issue by morisil** [openrndr/openrndr#212]
**Describe the bug**
While converting `openrndr-math` into kotlin mpp I noticed that one test there is permanently switched off

**To Reproduce**
uncomment the test, it will fail

**Expected behavior**
The test should be either removed or fixed.

**Context:**
 - OS and version: all
 - OpenRNDR version: 0.3.45 (latest)
 - Java Version: 15

**Comment by hamoid** [comment]
https://github.com/openrndr/openrndr/blob/master/openrndr-math/src/commonTest/kotlin/org/openrndr/math/transforms/TestTransforms.kt#L269
