### ISSUE TITLE
API Docs page is empty

### ISSUE THREAD

**Issue by megadix** [openrndr/openrndr#216]
**Describe the bug**
The page of [API reference documentation is empty](https://api.openrndr.org/)

**Screenshots**

![image](https://user-images.githubusercontent.com/1434231/113150053-f406b600-9233-11eb-8cef-09e71dff205e.png)

**Additional context**
A couple of weeks ago (today is March 31, 2021) the API Docs page was online, I don't know when exactly it did disappear :(

**Comment by ricardomatias** [comment]
It's back up!

**Comment by megadix** [comment]
Great! Thank you.
Closing issue
