### ISSUE TITLE
TIFF Image Support

### ISSUE THREAD

**Issue by sam-tsao** [openrndr/openrndr#223]
**Is your feature request related to a problem?**
OpenRNDR currently doesn't support TIFF (when saving a colorBuffer to disk). 

**Describe the solution you'd like**
Would be great if there would be TIFF support, since it writes faster.

**Comment by edwinRNDR** [comment]
Think we should add TIFF support through an ORX. In my experience TIFF is a complex format, that can be faster under certain conditions (mostly when compression is disabled). 

Note that the `ScreenRecorder` can be used to write png image sequences, which is handled through ffmpeg, which may be faster than using `ColorBuffer.saveToFile` when you are writing sequences of images.

**Comment by hamoid** [comment]
https://github.com/openrndr/orx/pull/185

**Comment by hamoid** [comment]
Make sure there's enough disk space before use :-)

**Comment by hamoid** [comment]
Since now there's a [tiff profile](https://github.com/openrndr/orx/tree/master/orx-jvm/orx-video-profiles#tiff-sequence) for the `ScreenRecorder` I'll close this issue. 

We can re-open it if saving single TIFF files is needed.
