### ISSUE TITLE
Fill does not treat ColorRGBa with LINEAR correctly

### ISSUE THREAD

**Issue by jbellis** [openrndr/openrndr#232]
In this program, I expect all three circles to be the same.  But the second is drawn much darker, I believe because LCHUV to RGB gives an RGB object with LINEAR linearity.

More generally it's not clear to me what problem Linearity is trying to help me solve, if I have to check it the results of transformations manually then it's going to be a source of errors.

`
package jbe.openrndr;

import org.openrndr.ApplicationKt;
import org.openrndr.Configuration;
import org.openrndr.PresentationMode;
import org.openrndr.Program;
import org.openrndr.color.ColorRGBa;
import org.openrndr.color.Linearity;

public class Test2 extends Program {
    @Override
    public void setup() {
        super.setup();
        getWindow().setPresentationMode(PresentationMode.MANUAL);
        getWindow().requestDraw();
    }

    @Override
    public void draw() {
        drawer.clear(ColorRGBa.Companion.getWHITE());

        var rgb = new ColorRGBa(0.4588235294117647, 0.33725490196078434, 0.13725490196078433, 1.0, Linearity.SRGB);
        drawer.setFill(rgb);
        drawer.circle(300, 300, 200);

        drawer.setFill(rgb.toLCHUVa().toRGBa());
        drawer.circle(600, 600, 200);

        drawer.setFill(rgb.toLCHUVa().toRGBa().toSRGB());
        drawer.circle(900, 900, 200);
    }

    public static void main(String[] args) {
        var c = new Configuration();
        c.setWidth(1200);
        c.setHeight(1200);
        ApplicationKt.application(new Test2(), c);
    }
}
`

**Comment by edwinRNDR** [comment]
Good question. Currently the renderer has no idea in which color space input and/or output reside so it treats all color data as-is. I'd gladly formalize this but I haven't found a way that doesn't force users to be aware of color spaces all the time. The default however is that rendering takes places in sRGB.  Currently the linearity in ColorRGBa is mostly there to assist converting between colorspaces. Thus user supplied colors through fill/stroke (and clear) are treated as-is and their linearity is ignored.  This sadly leaves it up to the user to convert RGB colors to the right linearity (which requires a toSRGB() by default).

**Comment by hamoid** [comment]
Is it intentional that `.toHSVa().toRGBa()` returns sRGB and `.toLCHUVa().toRGBa()` returns LINEAR?

```
        val c = ColorRGBa(0.458, 0.337, 0.137, 1.0, Linearity.SRGB)
        println(c)
        println(c.toHSVa().toRGBa())
        println(c.toLCHUVa().toRGBa())
```

**Comment by edwinRNDR** [comment]
> Is it intentional that `.toHSVa().toRGBa()` returns sRGB and `.toLCHUVa().toRGBa()` returns LINEAR?

More or less. The HSV transformation is defined as operations in sRGB space. LCHuv works on XYZ primaries (which is a linear transformation of linear RGB space). One is likely to work in sRGB when using HSV.

One could add a convention that all `toRGBa` functions output linear rgb ColorRGBas but then we are solving a problem that has no definition.

**Comment by hamoid** [comment]
I could mention it in the guide...

**Comment by jbellis** [comment]
I thought about this a bit more.  Usually if an API specifies type X but really it requires subtype Y, but the type system itself can't distinguish between the two, it should either throw an exception if X is not a Y, or silently derive Y from X. Is either of those possible here?

**Comment by edwinRNDR** [comment]
I decided to use sRGB textures and targets by default. This means that the graphics pipeline now assumes that all color inputs are in linear rgb. Assigning an srgb color to fill or stroke, or setting a ColorRGBa parameter on a shade style should result in a conversion to linear rgb.
