### ISSUE TITLE
Feature request: Support MacOS ARM 

### ISSUE THREAD

**Issue by ink404** [openrndr/openrndr#261]
### Motivation

MacOS ARM silicon doesn't appear to be supported currently, it would be a great addition to make this project even more portable.

### Proposed Solution

LWJGL version used by the project appears not to support apple arm architecture, there is a released version (3.3.x) that does, one approach is ilhaving the LWJGL version specified in clients' build.Gradle.kts

### Detailed Design

Update LWJGL for openrndr and orx libraries to use a client provided LWJGL or publish a version using the 3.3.0-SNAPSHOT version from LWJGL

### Open Questions

Not necessary if there's already a way to change the LWJGL version used by the project

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by AvneeshSarwate** [comment]
Any updates on this? Even a workaround for specifying the LWJGL version in the template project would be welcome

**Comment by hamoid** [comment]
OPENRNDR from the main branch uses lwjgl 3.3.0, so according to the above it might work. Have you tried?

**Comment by edwinRNDR** [comment]
OPENRNDR 0.4.0 has fully working support for MacOS ARM out of the box now
