### ISSUE TITLE
Feature request: make drawing a multisample colorBuffer throw an error

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#274]
### Motivation

The guide mentions that `The color buffers that are attached to a multi-sampled render target cannot be drawn directly. In order to use the color buffer it has to be resolved first. ` but if one tries drawing it nothing happens and there's no error either.

Throwing an error would be better than a blank screen.

Mentioned in Slack: https://openrndr.slack.com/archives/CBJGUKVSQ/p1639584201103000

### Possible solutions

Throw an error

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by edwinRNDR** [comment]
Fixed in 87845b851a02cc7c0aa2146e07718ddef99355a3
