### ISSUE TITLE
Polar arithmetic is broken

### ISSUE THREAD

**Issue by jbellis** [openrndr/openrndr#294]
### Operating System

Windows

### OPENRNDR version

master

### Java version

17

### Describe the Bug

Given Polar p1, p2,

p1 + p2 should be equal to Polar.fromVector(Vector2.fromPolar(p1), Vector2.fromPolar(p2))

some discussion on how to do this without actually converting twice here: https://math.stackexchange.com/questions/1365622/adding-two-polar-vectors

### Steps to Reproduce

new Polar(0, 1).plus(new Polar(90, 1));

**Comment by edwinRNDR** [comment]
Why is P(v1) + P(v2)  = P(v1 + v2) assumed?

**Comment by jbellis** [comment]
(1) [that's what people expect](https://www.google.com/search?q=add+polar+vectors)

(2) P(v1) + P(v2) = P(v1.theta + v2.theta, v1.radius + v2.radius) doesn't correspond to any useful calculation I can think of

**Comment by edwinRNDR** [comment]
But linear interpolation in polar space does use the current equality, and so do numerical differentiation and integration. I work under the assumption that a transformation to polar space is made explicitly to use the polar space's properties. To then have addition work in Euclidean space is nonsensical.

I close with a demonstration of why Polar arithmetic is how it is now.

```
val start = Polar(20.0, 30.0)
val end = Polar(40.0, 80.0)
val polarVelocity = (end - start) / 40.0
val polarPosition = start + polarVelocity * time
```
