### ISSUE TITLE
Feature request: ColorRGBa API changes

### ISSUE THREAD

**Issue by Vechro** [openrndr/openrndr#325]
### Motivation

Trying to build upon the openrndr-color package has pointed out some shortcomings of the existing API. I will try to list what I consider to be "sharp corners" of the API and possibly offer a solution.

### `rgb` method overloads
`rgb(r: Double, g: Double = r, b: Double = r, a: Double = 1.0)` is a convenient shorthand for specifying an RGB color or even a grayscale color when providing only one argument. Although on closer inspection one might notice that `rgb(1.0, 0.0)` is also a valid method call. This will return a magenta color, but I find it hard to believe this is desired behavior in the real world.

Perhaps `rgb` should not have default values for the color components (except for alpha) and instead it should have an overload for grayscale so we end up with two function signatures
1. `rgb(r: Double, g: Double, b: Double, a: Double = 1.0)`
2. `rgb(gray: Double, a: Double = 1.0)`

### There is no consistent name for the alpha parameter
Practically every openrndr-color color space has an alpha parameter in the constructor for specifying opacity. Common color types such as ColorRGBa/HSVa/HSLa call the parameter `a`. The less common ones such as ColorLCHABa/LCHUVa/LSHABa/LSHUVa call it `alpha`. Ideally we'd pick either one or the other name and abstract it to an interface for all color spaces to implement for consistent alpha naming. 
The first instinct would be to call it `a` because that's what ColorRGBa, probably the most common color space, calls it. This would be fine if it weren't for ColorLABa where `a` is one of the color space formula parameters and `alpha` is the alpha parameter.

This means we should consider the alternative and call the alpha parameter `alpha` which would be a notable breaking change for ColorRGBa.

### ColorRGBa.fromHex should also accept 4-digit and 8-digit hex codes for specifying transparency
This would match the behavior of the [CSS RGB hexadecimal notation](https://www.w3.org/TR/css-color-4/#hex-notation).

### Migrate two common colors from orx-color
This is more of a personal preference but I feel `ColorRGBa.CYAN` and `ColorRGBa.MAGENTA` should be moved to openrndr-color. They're part of the basic CMYK colors and should be available in openrndr without a dependency on orx.

### Proposed Solution

I've mostly mentioned what I would consider the solutions are, but to go in a bit more detail for ColorRGBa.fromHex, I believe [IntelliJ's hexadecimal color handling](https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/ui/ColorHexUtil.java) could be a source of inspiration.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by edwinRNDR** [comment]
I prefer your proposed `rgba(gray: Double, a: Double)` over what we have now.

--

I am asuming there is not that much code that accesses the `a`  argument by name.  Code like `ColorRGBa(1.0, 3.0, 0.2, a=0.5)` or `color.copy(a = 0.4)` is assumed to be uncommon.

Under that assumption we can change `OpacifiableColor` to include an `alpha` property

```kotlin
interface OpacifiableColor<T> {
    val alpha: Double
    fun opacify(factor: Double): T
}
```

Then in classes that already use `OpacifiableColor` (should be most/all of them) we create an alias property `a`  to keep things somewhat source compatible.

```kotlin
class ColorRGBa(val r: Double, val g: Double, val b: Double, override val alpha:Double) : OpacifiableColor<ColorRGBa> { 
    val a: Double 
         get() = alpha    
}
```
--

Ok on hexadecimal alpha notation.

-- 

Ok on migrating the primary colors to `openrndr-color`.
