### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by zhelenskiy** [openrndr/openrndr#363]
Is it still valid? https://github.com/openrndr/openrndr/blob/6267daaa42315cdf2b82e75e2d6211eb421a3c09/openrndr-math/src/commonMain/kotlin/org/openrndr/math/IntVector2.kt#L26

**Comment by edwinRNDR** [comment]
I have no idea,  worth checking out. Those `@transient`s were added around the times of Kotlin 1.6
