### ISSUE TITLE
Bug report: Inconsistent SIGSEGV Error with face.glyphForCharacter('a').shape(faceSize) in Various Scenarios

### ISSUE THREAD

**Issue by helloItIsThomas** [openrndr/openrndr#381]
### Operating System

Mac

### OPENRNDR version

0.4.3

### Java version (if applicable)

openjdk-20.0.2 | kotlin = "1.8.21"

### Describe the bug

When calling the function face.glyphForCharacter('a').shape(faceSize) in my OpenRNDR project, a fatal SIGSEGV error occurs, under different conditions. In a basic template program, a single call usually works without issues. However, with two calls, implementing oliveProgram, or inserting this call into a larger program, a similar fatal error consistently occurs.

### Steps to reproduce the bug

1   Initialize face.

2   In a basic program template, make a single call to face.glyphForCharacter('a').shape(faceSize). (Often, no error occurs.)

3   Introduce complexity: either make two calls to the same function, implement it within oliveProgram, or place it in a larger program. (Error occurs.)

4   Once the error appears, it persists even when reverting the code to a previously working state.

**Comment by edwinRNDR** [comment]
Fixed in https://github.com/openrndr/openrndr/commit/84bb84c4b5288e56b1c31097e2279d2e25b871f4
