### ISSUE TITLE
Feature request: add a method to get a pixel color from a ColorBuffer

### ISSUE THREAD

**Issue by tsu-na-gu** [openrndr/openrndr#399]
### Motivation

I request the function get image color from already rendered Image. It's simple draw Image to Buffer and getColor from the Buffer at target point.
here are ChatGPT writing the code

```kotlin
// オフスクリーンバッファを作成
val offscreenBuffer = renderTarget(width, height) {
    colorBuffer()
}

extend {
    // バッファに描画
    drawer.withTarget(offscreenBuffer) {
        // 描画処理
    }
}
fun getColorAt(x: Int, y: Int): ColorRGBa {
    val pixelData = offscreenBuffer.colorBuffer(0).read().getColor(x, y)
    return pixelData.toColorRGBa()
}

// 使用例
val colorAtPoint = getColorAt(100, 100)
println("Color at (100, 100): $colorAtPoint")
```

It's sure to need because easily cross line can find this method.

### Help make it happen!

I am not willing to submit a PR to implement this change.

**Comment by hamoid** [comment]
Hi! Thank you for your idea.

Have you seen the `shadow` object inside `ColorBuffer`?

https://guide.openrndr.org/drawing/colorbuffers.html#color-buffer-shadows

```
val offscreenBuffer = renderTarget(width, height) {
  colorBuffer()
}
val shadow = cb.shadow

drawer.withTarget(offscreenBuffer) {
  //draw here
}

shadow.download()

val colorAtPoint = shadow[100, 100]
println("Color at (100, 100): $colorAtPoint")
```

One needs to call `download` to update the shadow any time new content is drawn onto the render target because its `ColorBuffer` is in the GPU RAM, but the `shadow` is on the CPU RAM. Calling `download` copies the content from the first to the second.

I think that ChatGPT code is wrong because the `ColorBuffer.read()` method requires an argument.

**Comment by hamoid** [comment]
Closing this issue, since it is already possible to read pixel colors from a ColorBuffer.

**Comment by hamoid** [comment]
Do you think we need to improve the guide to make it more clear how to read pixel colors?

**Comment by tsu-na-gu** [comment]
I understand the approach but this libraly make more useful, like Processing getColor() method is useful. I think I would write this kind method after I understand kotlin's test future and make branch.

**Comment by tsu-na-gu** [comment]
I understand basic approach to get pixels from buffer. But I think it's still complecated way of approach. Like processing getColor or something is more user friendly. I think I would write this kind of method in extension but I have little knowledge about OpenGL. I would read Code and would study how to write extension, if I could write buffer implement extension if it wouldn't bother you.

**Comment by tsu-na-gu** [comment]
import org.openrndr.Extension
import org.openrndr.Program
import org.openrndr.color.ColorRGBa
import org.openrndr.draw.*

class PixelColorExtension : Extension {
    override var enabled: Boolean = true

    private lateinit var offscreenBuffer: RenderTarget
    private lateinit var pixels: ColorBufferShadow
    private lateinit var programRef: Program

    override fun setup(program: Program) {
        programRef = program

        offscreenBuffer = renderTarget(program.width, program.height, multisample = BufferMultisample.Disabled) {
            colorBuffer()
        }
        pixels = offscreenBuffer.colorBuffer(0).shadow
    }

    override fun afterDraw(drawer: Drawer, program: Program) {
        // 描画後にバッファにレンダリング
        drawer.withTarget(offscreenBuffer) {
            // 必要な描画処理をここに記述
        }
        pixels.download()
    }

    fun getPixelColor(x: Int, y: Int): ColorRGBa {
        return pixels[x, y]
    }
}

ChatGpt suggest this kind of code. It may not hard task to implement getPixelColor Extensition

**Comment by hamoid** [comment]
Hi! When you paste code it will look better if you use [code fences](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks):

````
```kotlin
fun main() {
  ...
}
```
````

If you write such an extension the color data you obtain will always be one frame old unless you manually call `pixels.download()` after drawing something into the render target.

I also don't think the code is going to become much simpler.

```kotlin
import org.openrndr.Extension
import org.openrndr.Program
import org.openrndr.application
import org.openrndr.color.rgb
import org.openrndr.draw.Drawer
import org.openrndr.draw.RenderTarget
import org.openrndr.draw.isolatedWithTarget
import org.openrndr.draw.renderTarget
import org.openrndr.math.Vector2
import kotlin.math.sin

// Extension
class PixelColorExtension(rt: RenderTarget) : Extension {
    override var enabled: Boolean = true

    private val pixels = rt.colorBuffer(0).shadow

    override fun afterDraw(drawer: Drawer, program: Program) = pixels.download()

    fun getPixelColor(x: Int, y: Int) = pixels[x, y]
}

// User code
fun main() = application {
    program {
        val rt = renderTarget(width, height) {
            colorBuffer()
        }
        val rtShadow = PixelColorExtension(rt)
        extend(rtShadow)
        extend {
            // Draw into the render target
            drawer.isolatedWithTarget(rt) {
                fill = rgb(sin(seconds) * 0.5 + 0.5)
                circle(Vector2.ZERO, 250.0)
            }

            // Show the render target
            drawer.image(rt.colorBuffer(0))

            // Read a color from the render target
            // Notice that afterDraw has not been called afer drawing into
            // the render target, therefore we will get an outdated color
            // from one frame ago.
            drawer.fill = rtShadow.getPixelColor(5, 5)

            // Draw a circle using the color
            drawer.circle(drawer.bounds.dimensions, 250.0)
        }
    }
}
```

Instead of an Extension you could create a `RenderTargetWithAutoShadow` or something like that, which extends RenderTarget, contains a shadow and downloads the shadow any time you draw into it. Maybe it's a fun exercise. 

When I started using OPENRNDR I was thinking of such ways to simplify things, but I think in my case it was maybe resistance to change. Processing hides some things from the user making them easier, but at the same time less flexible.

**Comment by hamoid** [comment]
Here an example of a RenderTarget-like class which automatically updates the shadow after drawing into it:

```kotlin
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.draw.Drawer
import org.openrndr.draw.isolatedWithTarget
import org.openrndr.draw.renderTarget
import org.openrndr.extra.noise.Random
import org.openrndr.math.Vector2

class ShadowedRenderTarget(width: Int, height: Int) {
    private val rt = renderTarget(width, height) {
        colorBuffer()
    }
    private val pixels = rt.colorBuffer(0).shadow
    fun draw(drawer: Drawer, draw: Drawer.() -> Unit) {
        drawer.isolatedWithTarget(rt) {
            draw()
        }
        pixels.download()
    }
    val image get() = rt.colorBuffer(0)
    fun getPixelColor(x: Int, y: Int) = pixels[x, y]

}

fun main() = application {
    program {
        val srt = ShadowedRenderTarget(width, height)
        extend {
            // Draw into the render target
            srt.draw(drawer) {
                fill = if(Random.bool(0.1)) ColorRGBa.WHITE else ColorRGBa.BLACK
                circle(Vector2.ZERO, 250.0)
            }

            // Show the render target
            drawer.image(srt.image)

            // Read a color from the render target
            drawer.fill = srt.getPixelColor(5, 5)

            // Draw a circle using the color
            drawer.circle(drawer.bounds.dimensions, 250.0)
        }
    }
}
```
