### ISSUE TITLE
Bug report: RenderTarget stretches new things drawn to it when window size is changes

### ISSUE THREAD

**Issue by TheCommCraft** [openrndr/openrndr#424]
### Operating System

Windows 11

### OPENRNDR version

0.4.4

### Java version (if applicable)

21

### Describe the bug

I tried working with RenderTargets to create a tile grid and it worked, but when I changed the size of the window and drew something new to the RenderTarget, it was stretched inwards. (The window was made bigger and the size of the content of the renderTarget was reduced) Everything that was on the renderTarget before resizing the window wasn't changed.

**Comment by hamoid** [comment]
Did you try calling `ortho(rt)` as mentioned in https://guide.openrndr.org/drawing/renderTargets.html#render-targets-and-projection-transformations ?

**Comment by TheCommCraft** [comment]
Oh, I didn't know that the renderTarget had a documentation

Abe Pazos ***@***.***> schrieb am Mo., 23. Dez. 2024, 21:31:
