### ISSUE TITLE
Inconsistent HiDPI support across operating systems

### ISSUE THREAD

**Issue by shi-weili** [openrndr/openrndr#62]
**Describe the bug**
The way OPENRNDR deals with screen scaling is different between macOS and Linux. 

On macOS, setting `width` and `height` in `configure { }` works as expected--app window will have the specified size in "points". On a Retina display, the actual # of pixels will be more than the # of points according to the scale factor in the OS configuration.

On Linux (tested on Kubuntu), however, setting `width` and `height` in `configure { }` will set the actual pixel size of the app window, regardless of the screen scaling setup of the OS. The values of `width` and `height` in `program { }` become the values you set in `configure { }` divided by `window.scale`. `window.size` also gets these scaled values.

But the app content isn't scaled while the app window is scaled. The content still follows the "point" metric according to the scale factor in the OS configuration. This results in normal-sized content in a small window with the content being cropped (see **Screenshots**).

**To Reproduce**
Put the following code in `openrndr-template` and run:

```
fun main() = application {
    configure {
        width = 768
        height = 576
    }

    program {
        println("width: $width")
        println("height: $height")
        println("window.size: ${window.size}")
        println("window.scale: ${window.scale}")
    }
}
```

**Expected behavior**
On Linux, expect the following output in the console:

```
width: 453
height: 340
window.size: Vector2(x=453.0, y=340.0)
window.scale: Vector2(x=1.6979166269302368, y=1.6979166269302368)
```

The values differ according to screen scaling setup in the OS, but you can see that `width` and `height` has changed from `configure { }` to `program { }` (divided by `window.scale`).

**Screenshots**
Running `C03_Color003.kt` in `openrndr-examples` results in cropped content, which demonstrates the description in **Describe the bug**.

![image](https://user-images.githubusercontent.com/918937/73129039-99772780-3fa8-11ea-98eb-f7ffc03b280c.png)

**Context:**
 - OS and version: Kubuntu 19.10 (KDE Plasma 5.16.5, KDE framework 5.62.0, Qt 5.12.4, Linux kernel 5.3.0-26-generic)
 - OpenRNDR version: 0.3.37
 - Java Version: Oracle Java 13.0.2 2020-01-14

**Comment by edwinRNDR** [comment]
Thanks for reporting @shi-weili . The behavior is definitely inconsistent as it is now.

Part of the problem seems to lie in how GLFW's `glfwGetWindowContentScale` behaves differently between platforms.
