### ISSUE TITLE
ShapeContour .offset() produces unexpected result

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#66]
The last segment of the .offset() contour seems to be too short.

```kotlin
            backgroundColor = ColorRGBa.WHITE

            val a = ShapeContour.fromPoints(
                listOf(
                    Vector2(50.0, 50.0),
                    Vector2(150.0, 50.0),
                    Vector2(60.0, 150.0),
                    Vector2(40.0, 60.0)
                ), false // <= true makes it crash
            )
            val b = a.offset(5.0, SegmentJoin.MITER)

            drawer.fill = null
            drawer.stroke = ColorRGBa.BLACK
            drawer.contour(a)
            drawer.stroke = ColorRGBa.RED
            drawer.contour(b)
```
![Screenshot from 2020-02-07 14-25-53](https://user-images.githubusercontent.com/108264/74033151-d3d3c200-49b5-11ea-8e7f-a5f7aa0ce08f.png)

**Context:**
 - OS and version: Ubuntu 19.04
 - OpenRNDR Template 0.3.9
 - Java Version: openjdk version "11.0.5" 2019-10-15

**Additional context**
A second issue with .offset() is that it crashes if closed == true.
I can open a second issue for this if desired.

**Comment by hamoid** [comment]
I see that `a` has 3 segments, `b` has 6.

**Comment by hamoid** [comment]
For my use case I will use this:
```
    fun fastOffset(line: ShapeContour, dist: Double): ShapeContour {
        var points = mutableListOf<Vector2>()
        var prevNorm = Vector2.ZERO
        line.segments.forEach { segment ->
            val norm = (segment.start - segment.end).normalized.perpendicular
            points.add(segment.start + (norm + prevNorm).normalized * dist)
            prevNorm = norm
        }
        points.add(line.segments.last().end + prevNorm * dist)

        return ShapeContour.fromPoints(points, false)
    }
```
![Screenshot from 2020-02-07 16-33-27](https://user-images.githubusercontent.com/108264/74042307-9710c680-49c7-11ea-883e-71ccc7ceb3a9.png)

which produces the green line. The resulting vertices are at the requested distance from the original vertices, but the segments are not parallel to the original ones. I will use it for smoothed curves with no sharp angles, so it should not be noticeable, and I think the algorithm does less computation than `offset()`. Does it make sense to add it to ShapeContour?

**Comment by edwinRNDR** [comment]
Thanks for your clear report @hamoid

**Comment by edwinRNDR** [comment]
It is not the main issue here, but I can close the contour properly in your example and generate a proper offset. When I add (repeat) the last point it will encounter NaNs caused by a zero division.  `fromPoints` should check the last point for repeat to prevent this 

To be clear this is what breaks it for me.
```
val a = ShapeContour.fromPoints(
                listOf(
                    Vector2(50.0, 50.0),
                    Vector2(150.0, 50.0),
                    Vector2(60.0, 150.0),
                    Vector2(40.0, 60.0),
                    Vector2(50.0, 50.0)
                ), true
            )
val b = a.offset(5.0, SegmentJoin.MITER)
```

**Comment by edwinRNDR** [comment]
d016de544d6a0ba52dffd932bc03bef6106ca702 addresses both the NaN issue and the omitted segment issue.

@hamoid Your `fastOffset` appears to work on shapes with linear segments only. I can see the point for having a speed over accuracy method, but I haven't figured out how it fits in yet.

**Comment by hamoid** [comment]
You're right about the linear-segments-only. And thanks for the insight.
I'm still learning and experimenting :) Feel free to close the issue. If there were people creating little useful functions there could be something like layer51 in the Flash times where people share such functions with others :)
