### ISSUE TITLE
mark Drawer.isolated and Drawer.isolatedWithTarget as inline

### ISSUE THREAD

**Issue by ylegall** [openrndr/openrndr#70]
**Describe the bug**
minor improvement: `Drawer.isolated()` and `Drawer.isolatedWithTarget()` functions could probably be marked as `inline` to avoid the allocation of the lambda argument.

**Context:**
https://github.com/openrndr/openrndr/blob/727bbde2a4507368e94dcc8b4920cad1a351ffbd/openrndr-core/src/main/kotlin/org/openrndr/draw/Drawer.kt#L780-L800

**Comment by edwinRNDR** [comment]
Hi @ylegall it is a fair point and I will look into it.  My only concern is in how inlining in general affects the readability of stack traces in case an exception is thrown inside inlined code.
