### ISSUE TITLE
Add social media dimensions as profiles

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#71]
This could be dealt either at top-level within `configuration/configure`. In a nutshell it would provide the right dimensions, f.ex:

```kotlin
configure {
	profile = WindowProfile.Instagram.Landscape // => width 1080, height 608
}
```

**Comment by morisil** [comment]
For my own purpose I made this, which is also dealing with other aspects.

https://github.com/xemantic/xemantic-openrndr/blob/master/xemantic-openrndr-core/src/main/kotlin/com/xemantic/openrndr/core/XemanticContext.kt

The problem I was trying to solve was to generate videos out of offscreen buffers which have different sizes than what I see on the screen, sometimes much bigger. Sometimes I just want to do full off screen rendering. So the window dimensions are not relevant to "canvas" dimensions which I need to also propagate to my shaders in consistent way. I haven't pushed the code of the most recent version. At this stage I see it more as a playground which I want to generalize one day. Here are my predefined formats:

https://github.com/xemantic/xemantic-openrndr/blob/master/xemantic-openrndr-core/src/main/kotlin/com/xemantic/openrndr/core/XemanticOpenrndrCore.kt

**Comment by morisil** [comment]
BTW it is also doing proper setup of logback logging unifying all the logging subsystems.

**Comment by edwinRNDR** [comment]
Have you considered solving this through extension functions for `Configuration`?

```
fun Configuration.instagramLandscape() {
   width = 1080
   height = 608
} 

//
application {
    configure {
        instagramLandscape()
    }
}
```
