### ISSUE TITLE
[Font] Add 3 channel Signed Distance Field font rendering

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#80]

**Comment by hamoid** [comment]
Here a post from someone who tried doing this:
https://web.archive.org/web/20190127093851/https://lambdacube3d.wordpress.com/2014/11/12/playing-around-with-font-rendering/

The comments can be interesting too. They mention a follow up paper that contains good descriptions:

https://dspace.cvut.cz/bitstream/handle/10467/62770/F8-DP-2015-Chlumsky-Viktor-thesis.pdf

**Comment by edwinRNDR** [comment]
Closing issue, stale feature request.
