### ISSUE TITLE
Rework uniform optimization message

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#81]
At the moment, when uniforms are removed this kind of message will be logged in the console: `[main] WARN org.openrndr.internal.gl3.ShaderGL3 - shader <unknown-vertex-shader> / <unknown-fragment-shader> does not have a uniform called 'color'`

There should be a way to set/have the name of the shader in question.

**Comment by edwinRNDR** [comment]
This has been in addressed in a1d87758aea951ff572c269631fb7bef2e797250
