### ISSUE TITLE
Add Feature Request issue template

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#87]
As title says.

* Example (taken from [bpmn-js](https://github.com/bpmn-io/bpmn-js) repo). The *name, about, labels* should show a table.. not sure why it isn't working.

---
name: Feature request
about: Suggest an idea or general improvement.
labels: "enhancement"
---

__Is your feature request related to a problem? Please describe.__

__Describe the solution you'd like__

__Describe alternatives you've considered__

__Additional context__

**Comment by edwinRNDR** [comment]
Can you please make a PR for this?

**Comment by edwinRNDR** [comment]
It's there, but it looks weird when I use the template

**Comment by hamoid** [comment]
I would replace the double underscores used for bold by double asterisks. That's what this markdown editor uses when pressing **B** for bold.
