### ISSUE TITLE
Keyboard pressedKeys should be based on an Enum

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#89]
At the moment it's hard to figure out what is the name of the key that is pressed down. For example, left shift is `left-shift` which makes sense but only after printing out the contents of the `pressedKeys` collection.

I suggest moving to something in the direction of `keyboard.pressedKeys.contains(Keys.LEFT_SHIFT)`.

**Comment by edwinRNDR** [comment]
It is complicated by the nature GLFW's key press events. See https://github.com/openrndr/openrndr/issues/64 for some of the details

**Comment by edwinRNDR** [comment]
Closing this as it is non-actionable.
