### ISSUE TITLE
Rename background() to a verb

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#94]
__Is your feature request related to a problem? Please describe.__

    stroke = ColorRGBa.GREEN
    fill = ColorRGBa.RED
    background(ColorRGBa.BLUE)

`stroke` and `fill` use an equal sign to assign a color, but `background` is a function instead even if it takes the same type of variable. 

__Describe the solution you'd like__

As what `background()` does is to clear the background, it could be renamed something like `clear()` or `clearBackground()`, so `stroke` and `fill` are nouns but this method is a verb.

__Additional context__

https://openrndr.slack.com/archives/CBJGUKVSQ/p1586173652005600

**Comment by edwinRNDR** [comment]
The only thing that worries me is it the prevalence of `drawer.background(...)` in existing OPENRNDR based programs. What are your ideas for dealing with that?

**Comment by hamoid** [comment]
Can we have deprecated methods? The during a few versions calling `drawer.background` would print a warning in the console suggesting to update the code. But how to avoid 60 warnings per second? Maybe checking against `frameCount`?

**Comment by edwinRNDR** [comment]
There's a `@Deprecated` annotation that will trigger both IntelliJ and the Kotlin compiler to emit warnings.

**Comment by hamoid** [comment]
Is using that annotation good enough? 

Would be great to have feedback from users...
