### ISSUE TITLE
Create Program extension function `namedTimestamp`

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#97]
`ScreenRecorder` and `Screenshots` already generate file names automatically that include a time stamp and the program name. These strings can be useful in other occasions, for example to save an svg, an xml file or for uploading a named result to a server.

One use case would be to save an image with Screenshots, and at the same time save a json or xml file with a matching name including the required configuration to recreate that image in the future.

The proposed idea is to extract the name-generation part already used in those two cases and make it available for other purposes. 

It was discussed [here](https://openrndr.slack.com/archives/CEASC1PB7/p1586527161040400)

**Comment by hamoid** [comment]
The lines which currently generate file names automatically are:

https://github.com/openrndr/openrndr/blob/master/openrndr-extensions/src/main/kotlin/org/openrndr/extensions/Screenshots.kt#L155

https://github.com/openrndr/openrndr/blob/master/openrndr-ffmpeg/src/main/kotlin/org/openrndr/ffmpeg/ScreenRecorder.kt#L82

If we replace them with a call to a function, what's a good location for that function?

**Comment by edwinRNDR** [comment]
I think `openrndr-core` in `org.openrndr.utils.NamedTimestamp` will do, unless there is a better idea?

**Comment by hamoid** [comment]
pick me
