### ISSUE TITLE
Add beforeScreenshot hook/listener

### ISSUE THREAD

**Issue by ricardomatias** [openrndr/openrndr#98]
__Describe the solution you'd like__

I want to be able to run code right before a screenshot is taken.

__Additional context__

This allows code that is only executed once (outside of an extend loop) to adapt before a screenshot is taken.

**Comment by edwinRNDR** [comment]
I am guessing this should be executed before drawing the frame that goes into the image?

**Comment by ricardomatias** [comment]
yes

**Comment by edwinRNDR** [comment]
I have the following thing working:
```kotlin
fun main() {
    application {
        program {
            var bgColor = ColorRGBa.PINK
            extend(Screenshots()) {
                beforeScreenshot.listen {
                    println("strike a pose")
                    bgColor = ColorRGBa.YELLOW
                }
            }
            extend {
                drawer.clear(bgColor)
            }
        }
    }
}
```
I think it's good to add an afterScreenshot that gives you a chance to restore values

**Comment by hamoid** [comment]
> I think it's good to add an afterScreenshot that gives you a chance to restore values

Or to save an accompanying xml with the configuration required to regenerate that screenshot in the future?

**Comment by edwinRNDR** [comment]
Right there with you! The `ScreenshotEvent` includes a `basename` property that makes sure all you have to do is add your favorite file extension and write to a file.
